# YAML 파일 : 콜론(:)과 공백 들여쓰기 2칸을 이용해 계층 구조를 나타냄
# YAML 파일과 프로퍼티 파일을 함께 사용하면 YAML 파일의 설정을 프로퍼티 파일이 덮어씀
# ${}(Placeholder)를 이용해 다른 프로퍼티나 환경 변수 값을 나타냄

spring:
  application:
    name: 01_mybatis_interface
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_boot1
    username: greenit
    password: ${spring.datasource.username}
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true